name: backend-push

# Controls when the action will run. 
on:
  # Triggers the workflow on pushes to any branch
  push:
    branches: 
      - "**"
    paths:
      - '/backend'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs: one called build and one called test
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Sets default working directory for all steps in job
    defaults:
      run:
        working-directory: backend
    
    strategy:
      matrix:
        python-version: [3.8]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip   # install/upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]
        then
          pip install -r requirements.txt
          pip install -e .
        fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
