# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on pushes to any branch
  push:
    branches: 
      - "**"
    paths:
      - 'frontend'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs: one called build and one called test
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install the node software package
      - name: install node
        run: actions/setup-node@v1

      - name: install node dependencies
        working-directory: frontend   # Have to specify where to find package.json
        run: npm install    # Install node dependencies defined in package.json
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: unit-test
        working-directory: frontend
        run: npm test
    
