name: frontend-push

# Controls when the action will run. 
on:
  # Triggers the workflow on pushes to any branch
  push:
    branches:
      - '**'
      - '!main'
    paths:
      - 'frontend/**'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs: one called build and one called test
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Sets default working directory for all steps in job
    defaults:
      run:
        working-directory: frontend
    
    # Test multiple versions of node
    strategy:
      matrix:
        node-version: [12.x]
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Configure the specified Node.js version on the runner
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: ls -la
      - run: echo $PWD
      - run: npm install   # install the package and packages it depends on
      - run: npm run build --if-present   # creates a production build
      - run: npm test
    
